image: monachus/hugo


stages:
    - gitlabPages
    # - deploy

# deploy:
#     stage: deploy
#     script:
#         - hugo -t cocoa
#     only:
#         - master

pages:
    stage: gitlabPages
    script:
        - hugo -t cocoa
    artifacts:
        paths:
            - public
    only:
        - master
