image: monachus/hugo
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - gitlabPages
    # - deploy

# deploy:
#     stage: deploy
#     script:
#         - hugo -t cocoa
#     only:
#         - master

pages:
    stage: gitlabPages
    script:
        - hugo -t cocoa --baseURL="cdn.lzane.com"
    artifacts:
        paths:
            - public
    only:
        - master
