dist: "trusty"
# addons:
#   apt:
#     packages:
#       - "python3"
#       - "python3-pip"

python: 
  - 3.6

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo -t cocoa --baseURL="https://www.lzane.com" 

before_deploy:
  - cp -r supplement/public/ public
  - pip install --user -U pip
  - pip install --user qiniu 

deploy:
  - provider: script
    script: python deploy.py
    skip_cleanup: true
    on:
      branch: master