dist: "trusty"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo -t cocoa --baseURL="https://www.lzane.com" 

before_deploy:
  - cp -r supplement/public/ public
  - pip3 install --user -U pip
  - pip3 install --user qiniu 

deploy:
  - provider: script
    script: python3 deploy.py
    skip_cleanup: true
    on:
      branch: master