dist: "trusty"
language: python
# addons:
#   apt:
#     packages:
#       - "python3"
#       - "python3-pip"

python: "3.6"

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - echo "skipping tests"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
